// @flow
import { push } from 'react-router-redux';
import type { SagaIterator } from 'redux-saga';
import { apply, call, put, takeLatest } from 'redux-saga/effects';
import { APP_VERSION } from '../App';
import type { Livedoc } from '../model/livedoc';
import type { FetchDocAction, ReloadDocAction } from '../redux/actions/loader';
import { actions, FETCH_DOC, RELOAD_DOC } from '../redux/actions/loader';

export function* watchFetchDoc(): SagaIterator {
  yield [takeLatest(FETCH_DOC, fetchDoc), takeLatest(RELOAD_DOC, reloadDoc)];
}

const fetchOptions = {
  headers: {
    'Accept': 'application/livedoc+json'
  },
  mode: 'cors',
  credentials: 'include',
};

function* fetchDoc(action: FetchDocAction): SagaIterator {
  try {
    console.log('Fetching documentation at', action.url);
    const response: Response = yield call(fetch, action.url, fetchOptions);
    yield* updateDocAndNavigateHome(response, action);
  } catch (error) {
    yield* handleError('Could not fetch documentation. Potential causes: a malformed URL, network issue, or a' +
            ' cross-origin request that is not allowed by the server. Please open the console for details.');
  }
}

function* reloadDoc(action: ReloadDocAction): SagaIterator {
  try {
    console.log('Reloading documentation from', action.url);
    const response: Response = yield call(fetch, action.url, fetchOptions);
    yield* updateDocWithResponse(response, action.url);
  } catch (error) {
    console.warn("Could not reload doc, keeping offline doc. Error:", error.message);
  }
}

function* updateDocAndNavigateHome(response: Response, action: FetchDocAction): SagaIterator {
  try {
    yield* updateDocWithResponse(response, action.url);
    yield put(push('/global'));
  } catch (error) {
    yield* handleError(error.message);
  }
}

function* updateDocWithResponse(response: Response, url: string): SagaIterator {
  if (!response.ok) {
    throw new Error(`Could not fetch documentation: HTTP ${response.status} ${response.statusText}`);
  }
  const data: Livedoc = yield apply(response, response.json);
  console.log('Fetched documentation:', data);
  const livedoc = ensureValidPayload(data);
  yield put(actions.fetchSuccess(livedoc, url));
}

function ensureValidPayload(data: ?Livedoc): Livedoc {
  if (!data) {
    throw new Error('Unable to read documentation: no response payload');
  }
  let metaData = data.livedocInfo;
  if (!metaData || !metaData.version) {
    throw new Error('Cannot read version info from payload, it was probably generated by an old version of Livedoc');
  }
  const dataVersion = metaData.version;
  if (dataVersion !== APP_VERSION) {
    throw new Error(`The fetched data was generated by Livedoc v${dataVersion}, it cannot be displayed in UI v${APP_VERSION}`);
  }
  return data;
}

function* handleError(errorDetail: string): SagaIterator {
  yield put(actions.fetchError(errorDetail));
}
