language: java

jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - BINTRAY_USER=joffrey-bion
    - BINTRAY_REPO_LIBS=maven
    - secure: 1BkjZaa/AgqZsriqWr/ABC5TvuYkHFBq+u81GVweqqlhtwwugHZIWUa8G4FWkQ8edChckDoF+rw0PpFLSs4JhPLO/JR/hR8Ho6ZN6+L9a5T+t6HaIvMKdEZFkUe+NZiykoYp51+ZO5QO/eY01P4o4dlUQzX//U8vgyu6lTgU97zOMkXaK01O7B6+Unpq9uw+NWQk5Jq2FEyJHpOx+uSkCjIzJ5NNhnxGU2Foomdd43hIDBqTRS+xR/+LoWC1AjwXOFpFwfJAeG2+9wEQV5hYDb92nFJBUK4reB45FP53ZDeiVcNw4cA3OJ+O47W1SHDGaaNaza+feDC6LmTnNU8YO+Fw/2Qt+whe4pZImAS2QTjLB1lyXBuG24a3ph62LrG6wxOzG8G/Rm/D4dtB64Zt6bCX5MghxGAqW6Brawogw3FcYvE/L/oXrufmiVgTPXqQBt3+hjfCT4DB/ccAyX8ZxTpTdWCpEpS78U78P7NiZexEtwsAXjWsqRQQOV9xavYbqOTG+gMV9SuqLUeGNtUhZ2oc3t4QvsWt5KwaC8tlHkOnylYWgRqJ/qvpTaX4C2adAUAsc5brfcCN0TaJOELfEdRQTvqKgvK7raQ+txfTb0MUhjnqIvBu48Bvvs1UKIe0VeW5peTtjN7UCwld3B8D3Oby8e7mmRzbcN8YctH3c38=
    - secure: 3I/HxTGoapxhE2ueEzb9EaGLRS29UKxjdwBb8K2lkNRUtInUbvmOZ4PeJR8oLy3GQ1gyElWgvloUkiLULRoYRsDg2kNg0JnTav/LNYjTKNGG3I52fNxdJ54ds51cD4a9qGH8ZSFjNiDMeYhEfEnLXFTtUdfVmuWAQlFjCjd1UcLbO+fCHkUHryqjsBucQl8+eqjtZUysCgpAAJgG1d3E+CVqTCY04KJOLHnkEojoVPy9+Vp6q/Y6MJauxdMCXVtqeKY5U9rd6w9hYKkjXV5xyojXUQLSkiRVD2K0SVsDBfWt1+EUgoMN3+pwpTNpfWijTsMiHxgZmEb+FLV6tNojvwdB75jMTcvOEvv6YwlG1l5iYQj3WJcCHmqzdWhPFCFxlzNs/d7kHztPnt7kWnUeAde0alyXj89uRW0oPtNHzlZrmufIMHVjwTVOln/ahfZ7YRbcAjsxVXVjWt+EyNWpkaaKL9DIYUFK5z/iQKdB6IY52WKGFcIIi82LBWZERb8w60yUnDD6FlN3FZWtruR8um19CvrwlgGUUQP0MF6ay8YaCPMP5xZmLPjhi8V5MnWPY5+Ex2tKrTEm9U6SRdDRGUOng/ewqcorGlz55sAvb/QgnwY3o19HD/wiP9onlYkFIlCxzTuxSMyaa9S5qJOd0HVLksV4thfLzbJg7rSGhL8=
    - secure: FeJVw1/iVapUwZcPbUZAqkPx2R67gxbh1b/HtEZWGujg9vSym+qOYToTRZUEg8Fyc94OeNGbE9iq8ndZLnJGs5w7gPGvw6JIQL6XvGnT9/u2awQCvGI/OASBPspw0icege8VtbIw6SFdspS+puGsi+Oauxow5P9yl+IyAmW5B6MvRPyc9ZbOfeux+KN6FEsvJ0BR830U+Zp2hlMymTO40Jt3TJ/QbBoDZYbwE9QyaAPKTkvlZBsyuGhA6JkI9mAFnofDEg7nHAAEfRTMwDFX5OEv6vwdj6KPs0MrQMxTi3Wg63/RuAVgrKQ/HyDCtzojQYb7N/zOraEzUXjeUzIzf7AefrufBU9bZSiKuPedjS/kw6ElqvyOOmcHRIwD/4j12qAlr+LDVFkAbXFMZ2hw7qsER+Y2TzHUjlMMi8ZZXgpCnbE+EvaqRWXnKhMmv5QSwJNseOJwl3w08gClKJz4ANz9HL95PJNMN7gAt0ALbSbng1jw77rCAuta2ZHwcw0VoE3RXqdnilY3tKCv/7nXof5JEYz5DZ1nYQbBkeIqpAXQdgKnJs4tDXSJWKqGfQcMYrkVADyyw88EytyRipFJcB6PIA1jjYFpWQ4EdtNnpXBhLHjeS8IK2w6BW1gmhySLDdZOA0azRDz55LeVxf78QorKFBSofvlaakUNnm3LNN0=
    - DOCKER_USERNAME=hildan
    - secure: zc7dob8xcsFP5xXdHvd5DIN1z+hopW1B4kFZE188QQGijCdSP3I71UaXjBHOSUtKQy6tnPpQEWsifSAdFLGtXQXvJCUN20a5f0x4jCpVLL6MizievvmZyFoK2IRfXOex/+BwGtNYQSxTKOQDzniqJukyA2/XsJqdlRnEZ6QBSlydis318rE/r6ialqZJSI5Mud6t2Z+pYQS+NEwMGO+j955Cn2xLrtiuZLqY7vmBzaBDsJV6YC46wXRkop+Hdg8D+5bDS/Q+WcWfMjXEsELGE213DNKJh0VJWMnviY1Ly58qNPF85qTUBv8YENTC5JOFt0cTyvG2oD6rSWTZqxNCqMrbhi9EgDqW9LJ/HDSmoBSMyhodMfFZy+mtU/ZVS6NrvH+WQqYaOu64el8tA3siLsCQoOvQgyO523aArxaYHjTnf+2HV2X9UkKSTbfp5fhCgFRQjtvRIKfleyxs2wMAllcg2i0jtzQmcSClM5PYev8Pacpa391AW0owheB0CMNuDMQIY7F6dfjI/911s9y+k42WdNuYoWvE+wqMmHLqQFvqV9Qb13oivYmTfehIXVrrcZFMui6dQMdZjWvIOkJx85pV40OqqjYDMfqgvREfUY8SaEADrdNmw6QtBeMz5t42/0FrDFY27i3OmlWG5K2PZcL7NMIJTiPd+fsuk6rk71Q=

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: ./gradlew bintrayUpload dockerPush
    on:
      tags: true

# These files change at every build, and should not be cached
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache Gradle's dependencies and wrapper download
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
