<h1>${apiInfo.name}</h1>
<hr>
<p>
    This is a generated documentation for ${apiInfo.name} v${apiInfo.version}, based on the code in the following 
    packages:
</p>
<ul>
    <#list config.packages as package>
        <li>${package}</li>
    </#list>
</ul>
<p>
    Check out the links at the top of this page to browse the APIs and Types documentation.
</p>
<small>
    This page was automatically generated by Livedoc v${livedocInfo.version}.
    Please refer to the documentation on how to customize it.
</small>
