<#-- @ftlvariable name="" type="org.hildan.livedoc.core.model.GlobalTemplateData" -->
<h1>${apiInfo.name!"About this documentation"}</h1>
<hr>
<p>
    This is a generated documentation for <#if apiInfo.version??>version ${apiInfo.version} of </#if>this API, based on
    the code in the following packages:
</p>
<ul>
    <#list livedocConfig.packages as package>
        <li>${package}</li>
    </#list>
</ul>
<p>
    Check out the links at the top of this page to browse the APIs and Types documentation.
</p>
<small>
    This page was automatically generated by Livedoc v${livedocInfo.version}.
    Please refer to the documentation on how to customize it.
</small>
