title: Livedoc
theme: jekyll-theme-cayman

# for dependencies inclusion doc
groupId: org.hildan.livedoc
latestVersion: 4.5.2

demo_url: http://livedoc-demo.hildan.org:8080/livedoc/index.html

# to use in tabs
emptyArray: []
